# Generated by Django 2.1.1 on 2018-10-25 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181022_2039'),
        ('petshow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='showcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('like', models.CharField(max_length=50, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshow.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
