# Generated by Django 2.1.1 on 2018-10-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshow', '0002_showcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcomment',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
