# Generated by Django 2.1.1 on 2018-10-22 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adopt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('picone', models.CharField(max_length=100, null=True)),
                ('pictwo', models.CharField(max_length=100, null=True)),
                ('introduce', models.CharField(max_length=300)),
                ('stat_time', models.CharField(max_length=50, null=True)),
                ('end_time', models.CharField(max_length=50, null=True)),
                ('require', models.CharField(max_length=300)),
                ('isFree', models.CharField(max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('onlooker', models.CharField(max_length=50)),
                ('like', models.CharField(max_length=50, null=True)),
                ('com_num', models.CharField(max_length=50, null=True)),
                ('share', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('citys', models.CharField(max_length=50, null=True)),
                ('areas', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('weixin', models.CharField(max_length=50, null=True)),
                ('qq', models.CharField(max_length=50, null=True)),
                ('pet_sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopt.petsex')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopt.pettype')),
                ('provid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopt.province', to_field='pycode')),
                ('state_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopt.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
