# Generated by Django 2.1.1 on 2018-10-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopt',
            old_name='require',
            new_name='yaoqiu',
        ),
    ]
