# Generated by Django 2.1.1 on 2018-10-23 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0004_auto_20181022_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='state_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adopt.state'),
        ),
    ]
