# Generated by Django 2.1.1 on 2018-10-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0005_auto_20181023_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='com_num',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='like',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='onlooker',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='share',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
