# Generated by Django 2.1.1 on 2018-10-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0006_auto_20181023_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='com_num',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='like',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='share',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
