# Generated by Django 2.1.1 on 2018-10-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('creat_datetime', models.DateTimeField(auto_now_add=True)),
                ('photo', models.CharField(max_length=300, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('login_time', models.CharField(max_length=50, null=True)),
                ('last_time', models.CharField(max_length=50, null=True)),
                ('login_num', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
