# Generated by Django 2.1.1 on 2018-10-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(default='https://wx.qlogo.cn/mmopen/vi_32/jQNyKqaK3ibLEm7L5z6UFBrJ5nVlvzZ9am4PjH2X93uj0ucTOGNcTSBsPbgmUgVicwgqomzaibYWIib0F5jlTgLmmw/132', max_length=300),
        ),
    ]
