# Generated by Django 2.1.2 on 2018-10-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='userbasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('idcard', models.CharField(max_length=20, unique=True)),
                ('leixing', models.CharField(max_length=20, unique=True)),
                ('bankcard', models.CharField(max_length=20, unique=True)),
                ('telephone', models.CharField(max_length=11, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
