# Generated by Django 2.1.2 on 2018-10-23 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopt', '0005_auto_20181023_0845'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lingyang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300, null=True)),
                ('state', models.CharField(default='领养中', max_length=20)),
                ('telepthone', models.CharField(max_length=11, null=True)),
                ('adopt_uer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopt.adopt')),
                ('lingyang_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
