# Generated by Django 2.1.1 on 2018-10-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='like',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='forum',
            name='lookers',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
