# Generated by Django 2.1.1 on 2018-10-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20181024_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='like',
            new_name='zan',
        ),
    ]
