# Generated by Django 2.1.1 on 2018-10-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20181025_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
